# Generated by Django 5.1.4 on 2024-12-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_image_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
