# Generated by Django 5.1.4 on 2024-12-18 20:29

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=board.models.user_directory_path, verbose_name='File'),
        ),
    ]
