# Generated by Django 5.1.4 on 2024-12-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_preferences_user_alter_userstat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
