# Generated by Django 5.1.4 on 2024-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_userstat_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='page_num',
            field=models.IntegerField(default=5),
        ),
    ]
